### ISSUE TITLE
Install issue in 2.79

### ISSUE THREAD

**Issue by winer222** [space928/Blender-O3D-IO-Public#22]
### Describe the bug
Fails to install due to incorrect except clause in crypto try catch

### To Reproduce
Try installing in 279

### Expected behaviour
Should install

### Screenshots
![](https://cdn.discordapp.com/attachments/561857130844651522/1055478553241735168/image.png)

### Additional context
Tested on clean

**Comment by space928** [comment]
Fixed in d491546bde15710fd520b9711f42306ddb691f04
