### ISSUE TITLE
Blender crashes when trying to load cfg without a defined [LOD] entry.

### ISSUE THREAD

**Issue by Westu7** [space928/Blender-O3D-IO-Public#61]
### Describe the bug
Blender crashes when trying to load cfg without a defined [LOD] entry.

### To Reproduce
Steps to reproduce the behaviour:
[Be sure to attach any relevant files (o3d, cfg, dds, etc...) to the issue or provide a link to them here]
1. Remove each [LOD] entry from the cfg file.
2. Import that cfg
3. See error

### Expected behaviour
The cfg file will be imported

**Comment by space928** [comment]
Hi, I can't manage to reproduce this bug on the latest version of the plugin. Any chance you could provide a CFG file and the error message you get?

**Comment by Westu7** [comment]
I can't reproduce the error anymore either, it could have been a Blender problem in an older version or another conflicting plugin
