### ISSUE TITLE
Lighting reversed

### ISSUE THREAD

**Issue by KCR58Game** [space928/Blender-O3D-IO-Public#69]
### Describe the bug
Me import an .o3d into blender, no matter edited or nothing edited, and export it back to an o3d, the lighting then flipped. As show in the pic below, when the obj (vehicle registration) is facing the sunlight, it becomes dark, oppositely, when it is in backlit, it becomes bright.

### Screenshots
![image](https://github.com/space928/Blender-O3D-IO-Public/assets/140614862/7cf97dc0-9bbe-48f0-981e-de2296f3324a)
![image](https://github.com/space928/Blender-O3D-IO-Public/assets/140614862/b352af15-1337-431e-93f9-5502ecce7513)

### Additional context
This happened to all .o3d I import-export. My Blender is v3.5.1

**Comment by space928** [comment]
This is a known issue, it will be fixed in the next release of the plugin (when I eventually have the time to do so). Please follow issue #51 for updates on this.
