### ISSUE TITLE
O3D importing error

### ISSUE THREAD

**Issue by FreeHK-Lunity** [space928/Blender-O3D-IO-Public#73]
### Describe the bug
v1.2.1 makes some meshes produce wrongly mapped models
downgrading to v1.1.4 works

### To Reproduce
Steps to reproduce the behaviour:

Using [GX7767's Citybus E500MMC](https://mega.nz/#!hZ1GiLoK!rD0mxbJ6Vt5uDOi9IudV27kbQQnk4E6gjz48oGuT48A), import 8320.cfg

### Expected behaviour
body appears normal

### Screenshots
![圖片](https://github.com/space928/Blender-O3D-IO-Public/assets/67418738/bb7c1d45-eb79-46ce-9a14-fd980410fa67)
![圖片](https://github.com/space928/Blender-O3D-IO-Public/assets/67418738/2c94f786-e4fe-4451-862e-66b3490daf8c)
![圖片](https://github.com/space928/Blender-O3D-IO-Public/assets/67418738/1714f16c-0b2c-4f35-b69c-ca8b1183b465)

![圖片](https://github.com/space928/Blender-O3D-IO-Public/assets/67418738/4625ca49-65db-4b42-9efd-b0f2deb9042b)

**Comment by lmaodick1239** [comment]
repeated #59
