### ISSUE TITLE
Lumière du mesh inversé

### ISSUE THREAD

**Issue by Nicolas011234** [space928/Blender-O3D-IO-Public#89]
Lorsque l'on export un mesh, la lumière est inversé, cet a dire qu'il est éclairé par le dessous, comme si le soleil venait du sol.

**Comment by space928** [comment]
Can you please provide the .blend file you're having trouble with?

**Comment by luminescentwatermelon** [comment]
I can reproduce this issue with almost any converted .o3d.
See attached a blend file where I encountered the problem. As shown in the pictures, the side of the bus in direct sunlight is not illuminated while the opposite side is.
[testfile.zip](https://github.com/space928/Blender-O3D-IO-Public/files/13942590/testfile.zip)
![OMSI2_20240115_204858](https://github.com/space928/Blender-O3D-IO-Public/assets/156710906/90a5fa38-38fa-44db-a5b1-88992a2998f4)
![OMSI2_20240115_204903](https://github.com/space928/Blender-O3D-IO-Public/assets/156710906/b32c831c-2f88-419f-ba81-eef32e1d2720)

**Comment by space928** [comment]
Please make sure you using the latest beta version of the plugin.
It works for me in the latest beta:
![image](https://github.com/space928/Blender-O3D-IO-Public/assets/15130114/336340a2-f289-4ba6-8ac0-ca812fbc203d)
https://github.com/space928/Blender-O3D-IO-Public/releases/tag/v1.2.3

**Comment by luminescentwatermelon** [comment]
Thanks for the information, an upgrade to the last beta solved this issue!
